version: '3' 
services:
 zoo:
    image: zookeeper
    restart: on-failure
    hostname: zoo
    ports:
      - 2181:2181
    networks:
      - network
# zookeeper container is started with zookeeper as base image mapping the default ports
# networks is specified so that all the containers run in the same network so that they can communicate

 orchestrator:
    build: ./orchestrator
    image: orchestrator_image:latest
    container_name: orchestrator
    depends_on:
      - "rabbitmq"
      - "zoo"
    restart: on-failure
    ports:
      - "80:5000"
    networks:
      - network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
# orchestrator container is started from specified directory in the build 
# depends on specifies that this container is dependent on the specifed containers   
# volumes is specified so that the docker sdk commands can execute on the host
# port mapping indicates that all the requests to the port 80 is routed to the localhost 5000
# which is default port for flask application
        
 rabbitmq:
    build: ./rabbitmq
    image: rabbitmq_image:latest
    container_name: rabbitmq
    restart: on-failure
    ports:
      - "5672:5672"
    networks:
      - network

 slave:
    build: ./slave
    image: slave_image:latest
    container_name: slave
    depends_on:
      - "rabbitmq"
      - "zoo"
    restart: on-failure
    networks:
      - network
         
 master:
    build: ./master
    image: master_image:latest
    container_name: master
    depends_on:
      - "rabbitmq"
      - "zoo"
    restart: on-failure
    networks:
      - network

networks:
       network: {}
