version: '3' 
services:
 zoo:
    image: zookeeper
    restart: on-failure
    hostname: zoo
    ports:
      - 2181:2181
    networks:
      - network

 orchestrator:
    build: ./orchestrator
    image: orchestrator_image:latest
    container_name: orchestrator
    depends_on:
      - "rabbitmq"
      - "zoo"
    restart: on-failure
    ports:
      - "80:5000"
    networks:
      - network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
   
        
 rabbitmq:
    build: ./rabbitmq
    image: rabbitmq_image:latest
    container_name: rabbitmq
    restart: on-failure
    ports:
      - "5672:5672"
    networks:
      - network

 slave:
    build: ./slave
    image: slave_image:latest
    container_name: slave
    depends_on:
      - "rabbitmq"
#      - "orchestrator"
      - "zoo"
    restart: on-failure
    networks:
      - network
         
 master:
    build: ./master
    image: master_image:latest
    container_name: master
    depends_on:
      - "rabbitmq"
 #     - "orchestrator"
      - "zoo"
    restart: on-failure
    networks:
      - network

networks:
       network: {}
